version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:5050"

  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis-container
    networks:
      - app-network

  redis-container:
    image: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
