name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: <docker-hub-username>/<image-name>:latest
