name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # Exécute ce workflow pour chaque push sur la branche dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilise le secret DOCKER_USERNAME
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilise le secret DOCKER_PASSWORD

      # Étape 3: Construction et push de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Le chemin vers le Dockerfile et les sources
          push: true  # Pousse l'image vers Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/rapaldoos:latest  # Remplace `my-app` par le nom de ton application

      # Étape 4: Tester le conteneur Docker localement
      - name: Run Docker container
        run: |
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker ps  # Liste les conteneurs pour vérifier qu'il tourne correctement
